apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: image-registry.openshift-image-registry.svc:5000/net-apps/webapp:2
          ports:
            - containerPort: 5020
          readinessProbe:
            httpGet: { path: /healthz, port: 5020 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 5020 }
            initialDelaySeconds: 10
          volumeMounts:
            - name: webappdata
              mountPath: /var/webappdata
      volumes:
        - name: webappdata
          PersistentVolumeClaim:
            claimName: webapp-data
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - name: http
      port: 5020
      targetPort: 5020
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webapp
spec:
  to:
    kind: Service
    name: webapp
  port:
    targetPort: http
